In [63]:
!ls

checkins.dat  fsq  fsq.zip  Untitled.ipynb

In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv('checkins.dat',sep='|',low_memory=False, skipinitialspace=True).dropna()

In [66]:
df

,id,user_id,venue_id,latitude,longitude,created_at
1,984222,15824,5222,38.895112,-77.036366,2012-04-21 17:43:47
3,984234,44652,5222,33.800745,-84.410520,2012-04-21 17:43:43
7,984291,105054,5222,45.523452,-122.676207,2012-04-21 17:39:22
9,984318,2146539,5222,40.764462,-111.904565,2012-04-21 17:35:46
10,984232,93870,380645,33.448377,-112.074037,2012-04-21 17:38:18
11,984483,1030290,955969,32.221743,-110.926479,2012-04-21 17:58:54
12,984685,304253,23558,40.650000,-73.950000,2012-04-21 18:19:34
13,984470,720850,749715,33.448377,-112.074037,2012-04-21 17:02:47
15,984610,1639666,442605,33.414768,-111.909309,2012-04-21 18:04:58
18,984653,1647192,23558,42.358431,-71.059773,2012-04-21 18:23:22
19,984251,298547,77014,33.448377,-112.074037,2012-04-21 17:34:33
20,984528,2046311,15682,33.414768,-111.909309,2012-04-21 18:18:29
25,984438,2096701,4432,33.448377,-112.074037,2012-04-21 18:21:19
26,984277,1648816,18006,33.248664,-111.634299,2012-04-21 17:49:30
27,984320,349414,819,32.840678,-117.258794,2012-04-21 17:27:36
29,984359,1861538,819,34.052234,-118.243685,2012-04-21 17:18:22
34,984294,1447044,1135957,33.414768,-111.909309,2012-04-21 17:33:12
35,984336,2064557,111071,33.448377,-112.074037,2012-04-21 16:25:00
38,984527,1243334,989443,34.483901,-114.322455,2012-04-21 18:22:59
40,984326,2046338,989443,34.048928,-111.093731,2012-04-21 17:56:27
41,984454,2098254,610703,32.715329,-117.157255,2012-04-21 17:49:30
42,984395,1508584,410624,33.448377,-112.074037,2012-04-21 17:58:10
46,984231,1868751,21948,38.895112,-77.036366,2012-04-21 15:53:38
47,984322,1096457,10935,33.745851,-117.826166,2012-04-21 18:10:08
49,984474,2146888,10935,34.096111,-118.105833,2012-04-21 17:39:56
50,984355,966186,10935,34.052234,-118.243685,2012-04-21 18:03:47
52,984345,482032,10935,37.629349,-122.400087,2012-04-21 18:04:38
53,984508,2146895,10935,4.598056,-74.075833,2012-04-21 17:38:25
54,984381,28655,10935,33.804167,-118.158056,2012-04-21 17:59:40
55,984346,2098173,11195,40.735657,-74.172367,2012-04-21 18:17:31
...,...,...,...,...,...,...
1021885,936189,610763,7491,41.499495,-81.695409,2012-04-11 05:46:31
1021887,936836,610763,64,41.499495,-81.695409,2012-04-11 11:19:55
1021890,937236,287341,9310,30.267153,-97.743061,2012-04-11 13:04:51
1021895,938393,379311,11138,39.739154,-104.984703,2012-04-11 17:12:13
1021896,938627,503977,6562,28.538335,-81.379237,2012-04-11 18:09:54
1021898,938806,287341,12004,30.267153,-97.743061,2012-04-11 17:17:49
1021901,940180,1028835,16436,42.129224,-80.085059,2012-04-11 21:58:20
1021902,940219,373497,7489,40.715972,-74.001437,2012-04-11 22:14:12
1021912,943071,404031,1095987,33.448377,-112.074037,2012-04-12 09:25:48
1021915,943920,706143,4432,35.960638,-83.920739,2012-04-12 16:53:29
1021916,944155,872108,54467,33.103174,-96.670550,2012-04-12 19:06:15
1021918,944731,502383,23558,41.650111,-70.241131,2012-04-12 20:34:27
1021923,946195,354912,29137,39.867891,-75.131565,2012-04-12 20:34:29
1021925,946253,281860,29488,28.538335,-81.379237,2012-04-12 21:50:52
1021936,949275,872108,610705,33.103174,-96.670550,2012-04-13 00:55:03
1021939,949841,281860,9822,28.538335,-81.379237,2012-04-13 01:32:08
1021940,951412,919527,112490,47.606209,-122.332071,2012-04-13 01:29:20
1021943,952256,1028835,8595,42.129224,-80.085059,2012-04-13 02:42:32
1021947,953584,174305,916378,28.320007,-80.607551,2012-04-13 05:04:27
1021949,953695,146164,4202,30.267153,-97.743061,2012-04-13 03:33:53
1021952,954162,285893,42311,33.448377,-112.074037,2012-04-13 03:28:53
1021953,954283,709109,684720,33.448377,-112.074037,2012-04-13 06:26:18
1021954,954361,81625,5222,37.629349,-122.400087,2012-04-13 06:27:38
1021955,954428,626076,950644,40.850100,-73.866246,2012-04-13 06:29:25
1021957,954925,674797,7491,33.748995,-84.387982,2012-04-13 05:26:29
1021959,955561,626076,20073,40.850100,-73.866246,2012-04-13 09:56:48
1021960,955892,674797,2297,33.748995,-84.387982,2012-04-13 10:56:03
1021961,956377,845102,11195,42.765366,-71.467566,2012-04-13 12:08:45
1021962,956119,1139114,29488,42.439479,-83.743830,2012-04-13 11:36:44
1021964,956733,960666,60,42.331427,-83.045754,2012-04-13 21:56:19

In [67]:
df.columns

Index(['id    ', 'user_id ', 'venue_id ', 'latitude      ', 'longitude     ',
       'created_at      '],
      dtype='object')

In [68]:
from sklearn.cluster import MeanShift

In [70]:
clustering = MeanShift(bandwidth=0.1).fit(df[['latitude      ', 'longitude     ']].values[:100000,:])

clustering.labels_

array([ 5,  7, 30, ..., 25, 19,  4])

In [71]:
clustering.cluster_centers_.shape

(3231, 2)

In [80]:
len([n for n in clustering.labels_ if n == 0])

12506

In [105]:
def cx(x):
    print(x.id)
    return len([n for n in clustering.labels_ if n == x.id])

In [112]:
clust_centers = pd.DataFrame(clustering.cluster_centers_)
clust_centers['id'] = clust_centers.index

In [109]:
val, counts = np.unique(clustering.labels_, return_counts=True)

In [114]:
clust_centers['count'] = counts

In [119]:
clust_centers[clust_centers['count'] > 15].iloc[:, :2]

              0           1
0     40.717716  -73.991835
1     33.449438 -112.002140
2     33.446380 -111.901888
3     41.878244  -87.629843
4     37.688682 -122.409330
5     38.886165  -77.048783
6     33.357345 -111.822654
7     33.766636  -84.393289
8     42.363219  -71.073688
9     47.606245 -122.332044
10    36.117229 -115.171073
11    34.060398 -118.248709
12    44.977948  -93.267301
13    30.267184  -97.743119
14    40.766876  -73.833353
15    39.735830 -104.986580
16    39.951680  -75.162736
17    34.035487 -118.438998
18    32.980893 -117.078118
19    32.803021  -96.769897
20    37.347871 -121.947287
21    28.543502  -81.376429
22    32.711344 -117.153639
23    32.221713 -110.926535
24    34.127402 -118.351884
25    29.762698  -95.382314
26    43.040533  -87.914333
27    33.817306 -117.891249
28    37.390292 -122.087286
29    25.785812  -80.217938
...         ...         ...
571  -33.050462  -71.616452
572   60.169954   24.937730
573   50.111512    8.680506
575   44.058173 -121.315310
576   43.685271  -79.759924
577   43.680856  -72.287952
578   43.096171  -88.402632
579   42.765354  -78.782601
581   42.115474  -79.286368
582   42.059813  -70.951257
583   41.641871  -88.051727
584   41.634591  -72.635234
585   41.255845  -75.887471
588   38.041182 -122.150053
589   37.270702  -76.707457
590   37.204643  -80.412689
591   36.825228 -119.702919
592   35.528078 -108.742584
593   34.935238  -82.234904
594   32.319940 -106.763654
595    9.958968  -84.105633
615   30.408167  -86.528320
636   35.111360  -89.797982
657   41.486201  -70.597742
672   32.598960  -96.895365
684   41.577224  -73.415723
727   41.220398  -73.666619
884   41.618532  -88.445568
1343  39.249469  -77.182127
1350  38.658779  -76.885687

[592 rows x 2 columns]

In [61]:
offices = np.array([[33.751277, -118.188740],
[25.867736, -80.324116],
[51.503016, -0.075479],
[52.378894, 4.885084],
[39.366487, 117.036146],
[-33.868457, 151.205134]])

In [62]:
clustering.predict(offices)

array([  48,  317,   55,  319, 3720,  251])

In [73]:
from sklearn.metrics.pairwise import euclidean_distances

In [129]:
dist_matrix = pd.DataFrame(euclidean_distances(clust_centers[clust_centers['count'] > 15].iloc[:, :2], offices))

In [134]:
dist_matrix['id'] = clust_centers[clust_centers['count'] > 15].id.values

In [135]:
dist_matrix

,0,1,2,3,4,5,id
0,44.742571,16.143720,74.699066,79.734255,191.032760,237.227259,0
1,6.193959,32.572679,113.373317,118.410081,229.114704,271.679532,1
2,6.294241,32.474475,113.274833,118.311609,229.014565,271.581649,2
3,31.621097,17.598580,88.081797,93.108944,204.681402,250.558794,3
4,5.772048,43.713842,123.111360,128.139261,239.451355,282.816724,4
5,41.459174,13.424131,78.000478,83.037415,194.085524,239.568541,5
6,6.378262,32.376722,113.210850,118.247687,228.937678,271.482828,6
7,33.795454,8.885426,86.163056,91.197829,201.507260,245.114510,7
8,47.895654,18.912202,71.584087,76.616243,188.133702,234.987538,8
9,14.461227,47.299353,122.318651,127.306621,239.509966,285.413235,9
10,3.834585,36.323031,116.119414,121.152477,232.229952,275.416558,10
11,0.314884,38.799413,119.453578,124.488948,235.344678,277.884333,11
12,27.333428,23.080863,93.419977,98.431015,210.378298,256.872589,12
13,20.740355,17.965991,99.949630,104.983217,214.971929,257.077057,13
14,44.906781,16.251596,74.535151,79.570292,190.874637,237.092290,14
15,14.495237,28.294190,105.568963,110.596698,222.023034,266.555408,15
16,43.470473,14.999911,75.970583,81.006723,192.199773,238.100452,16
17,0.378688,38.980205,119.645464,124.680831,235.535481,278.062769,17
18,1.351655,37.435994,118.459641,123.496174,234.201333,276.486417,18
19,21.439823,17.848302,98.486042,103.522703,213.906763,256.781429,19
20,5.202131,43.177331,122.691099,127.719936,238.991958,282.283564,20
21,37.178854,2.875254,84.480671,89.493991,198.707541,240.809958,21
22,1.467274,37.459962,118.576652,123.613358,234.284328,276.494667,22
23,7.421535,31.255097,112.515445,117.552725,228.074619,270.334834,23
24,0.409983,38.914434,119.545890,124.581167,235.446326,278.000760,24
25,23.152577,15.553779,97.754970,102.786397,212.635450,254.665061,25
26,31.667492,18.775418,88.245554,93.268090,204.983407,251.183423,26
27,0.304731,38.399026,119.135805,124.171496,234.992924,277.478334,27
28,5.333020,43.323570,122.825283,127.853983,239.131598,282.429737,28
29,38.797299,0.134109,84.167620,89.161182,197.721037,238.988013,29
...,...,...,...,...,...,...,...
562,81.433718,59.558186,110.758302,114.676326,202.074286,222.823087,571
563,145.544265,110.709974,26.472182,21.513001,94.418761,157.437861,572
564,127.919752,92.247403,8.865865,4.421114,108.887099,165.426433,573
565,10.770680,44.846069,121.468194,126.474400,238.397626,283.443031,575
566,39.692041,17.826465,80.067021,85.090284,196.843453,243.637926,576
567,46.962526,19.541934,72.634891,77.661660,189.373250,236.565119,577
568,31.217612,19.028436,88.726326,93.748423,205.472630,251.665324,578
569,40.423971,16.967786,79.190642,84.218179,195.848242,242.419263,579
570,39.791386,16.280845,79.765223,84.794876,196.341759,242.692996,581
571,47.962606,18.709192,71.502098,76.535182,188.006696,234.773432,582
572,31.152866,17.565287,88.527184,93.554981,205.100495,250.889727,583
573,46.230602,17.541739,73.227753,78.261355,189.684941,236.231286,584
574,42.961796,16.014922,76.501390,81.534826,192.932868,239.195970,585
575,5.839117,43.561472,122.814586,127.841684,239.189871,282.655364,588
576,41.630316,11.962770,77.942407,82.979517,193.754938,238.757050,589
577,37.933570,11.337253,81.599699,86.636990,197.460670,242.277117,590
578,3.426647,40.874892,120.524528,125.555116,236.752704,279.979947,591
579,9.611809,30.015522,109.835051,114.870349,225.811356,269.051473,592
580,35.973324,9.266645,83.813259,88.849162,199.320314,243.368445,593
581,11.514396,27.215438,108.399064,113.436336,223.910706,266.324613,594
582,41.565997,16.352026,93.738864,98.583963,203.280145,239.357474,595
583,31.836435,7.688151,88.989248,94.016611,203.761486,246.269526,615
584,28.423317,13.236266,91.207532,96.244744,206.877893,250.680508,636
585,48.215476,18.399424,71.230093,76.264722,187.645861,234.253795,657
586,21.324531,17.886187,98.648131,103.684645,214.038527,256.849713,672
587,45.451826,17.161408,74.008869,79.042346,190.464699,236.952696,684
588,45.144291,16.733992,74.306044,79.340293,190.711777,237.077290,727
589,30.766052,17.721330,88.921177,93.948901,205.494055,251.258322,884
590,41.373571,13.745649,78.074225,83.110823,194.218308,239.806114,1343
591,41.593578,13.245134,77.876713,82.913814,193.923124,239.344151,1350

In [137]:
dist_matrix.min(axis = 0)

0     0.070848
1     0.022674
2     0.050058
3     0.009353
4     9.267575
5     0.007835
id    0.000000
dtype: float64

In [138]:
dist_matrix.min(axis = 0)[5]

0.007834758333930724

In [139]:
dist_matrix[dist_matrix[5] == dist_matrix.min(axis = 0)[5]]

              0           1           2           3          4         5   id
417  277.748513  239.108983  173.702814  169.843186  80.806596  0.007835  420

In [140]:
clust_centers[clust_centers['id'] == 420]

            0           1   id  count
420 -33.86063  151.204776  420     28